# NextDNS Rewrites Configuration
# Note: API key should be set via NEXTDNS_API_KEY environment variable
profile_name: "Main"

rewrites:
  # A record example
  - name: "example.com"
    content: "1.1.1.1"
  # CNAME record example
  # Although it is possible to create CNAME records
  # From my testing CNAME records don't actually resolve / work
  # See: https://help.nextdns.io/t/p8yx4pk?r=p8y1ct8
  # - name: "example.org"
  #   content: "example.com"
